### ISSUE TITLE
streamtransfer unit test image missing entrypoint for deployment

### ISSUE THREAD

**Issue by laurieaw63** [fybrik/fybrik#727] opened 2021-07-20 18:01 UTC
When the streamtransfer unit test ran the streamtransfer deployment is trying to access an entry point that is not part of the mover image. Is this entrypoint correct, if so where does it exist.

The streamtransfer_deployment.go code is specifying the following:
```
						Args:            []string{"/etc/mover/conf.json"},
						Command:         []string{"/streaming-entrypoint.sh"},
```

This is the error I am seeing:

```
  Warning  Failed     35s               kubelet, worker11.cpstreamsx8.cp.fyre.ibm.com  Error: container create failed: time="2021-07-20T16:29:59Z" level=error msg="container_linux.go:366: starting container process caused: exec: \"/streaming-entrypoint.sh\": stat /streaming-entrypoint.sh: no such file or directory"
  ```

**Comment by froesef** [comment] 2021-07-21 22:12
Which mover image did you use? I'll adapt the streamtransfer_deployment.go to be more similar to the batchtransfer code. But the `/streaming-entrypoint.sh` should be there in the mover image. (The dummy-mover does currently not have a streaming endpoint. I'll add this as well.)

**Comment by laurieaw63** [comment] 2021-07-22 12:54
The image being used is the one built by the test/dummy-mover/Dockerfile.dummy-mover.

**Comment by froesef** [comment] 2021-08-23 12:39
I changed the stream binary to `/stream` some time ago and added it to the dummy image as well. 
Closing this issue. Please re-open and contact me if you find that the issue is not resolved.

**Closed by froesef** 2021-08-23 12:39 UTC
