### ISSUE TITLE
Measure performance of control plane

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#980] opened 2021-11-23 08:40 UTC
Understand the overall performance of the control plane and its associated components.  
Measure:
- end to end time for the scenario
- data policy opa connector
- katalog connector
- deployment of data plane components (ex: arrow-flight read module)
- admin config policy evaluation

- [x] Test1: Test the quick start scenario which uses the katalog and opa connectors and deploys and arrow-flight server on kind
- [x] Test2: Test a scenario similar to the quick start scenario but that uses a pre-deployed arrow-flight server (config module) on kind
- [x] Test3: Repeat test1 on open shift
- [ ] Test4: Repeat test2 on open shift

**Comment by shlomitk1** [comment] 2021-11-24 12:56
I have tested a quick-start scenario when opa and katalog connectors have been deployed on kind, no webhooks deployed.
`FybrikApplication controller:`
- Validation of FybrikApplication: 1 ms
- Getting response from the catalog connector: 14-25 ms
- Getting response from the policy manager: 29-52 ms
- Adminconfig: initialization - ~20 ms, each subsequent evaluation 2-4 ms
- Building a plotter - 1ms
- Applying a plotter resource - 10-40 ms, depending on the machine load
- Overall reconcile - 95-98 ms, quite consistent between runs
`Plotter controller` - overall time consists of either getting a blueprint to check the status or creating a new blueprint, the processing time can be neglected. ~10ms to check the status, 12-20ms to generate a blueprint
`Blueprint controller`
Helm release installation: 2.3-2.5s
Helm resources status check: 30-80ms (mostly kubectl get operations)
** Although, I've tried a helm release with a single configmap, results were not much better (it took less time to check one resource than four resources, but helm install still lasts over 2 sec.)
End-to-end scenario takes ~5s. Multiple reasons/problems:
- Extra reconciles caused by status update or finalizer update, or Requeue requests during the reconcile.
- Problems with updating status (not the latest version). Causes another reconcile.
- Idle cycles. For example, blueprint controller checks resource status again and again, while plotter controller is waiting and can't update the status.
- Context switches? Manager is a single process, there are several controllers sharing the run-time.
Perhaps, some of the problems are specific to kind, I'll check on open shift clusters.

**Comment by roytman** [comment] 2022-05-01 08:01
@shlomitk1, @simanadler, can we close it?

**Comment by shlomitk1** [comment] 2022-05-01 12:54
Not yet.

**Comment by simanadler** [comment] 2022-06-07 14:33
@shlomitk1 Can you please rerun the tests on v0.7.0?  
Also, were any of the issues you raised (extra reconciles, updating status, etc) addressed already?

**Comment by shlomitk1** [comment] 2022-06-08 11:16
Problems with updating status have been resolved.

**Comment by shlomitk1** [comment] 2022-06-13 19:08
I've focused on Helm operations as they take most of the run time. 
The experiment was done on an OS cluster for 0.7 version, application that required installation of the arrow-flight module.
The script below starts an application, adds a dataset, waits for its readiness, removes a dataset, deletes the application:
```
#!/usr/bin/env bash
echo "Create empty fybrikapplication"
kubectl  apply -f app-empty.yaml
while [[ $(kubectl get fybrikapplication demo-app -n default  -o 'jsonpath={.status.ready}') != "true" ]]; do echo "waiting for FybrikApplication" && sleep 5; done
echo "Add asset"
kubectl  apply -f app-dev.yaml
while [[ $(kubectl get fybrikapplication demo-app -n default -o 'jsonpath={.status.assetStates.default/paysim-csv.conditions[?(@.type == "Ready")].status}') != "True" ]]; do echo "waiting for asset" && sleep 5; done
echo "Remove asset"
kubectl  apply -f  app-empty.yaml
while [[ $(kubectl get fybrikapplication demo-app -n default  -o 'jsonpath={.status.ready}') != "true" ]]; do echo "waiting for FybrikApplication" && sleep 5; done
kubectl delete fybrikapplications.app.fybrik.io demo-app -n default
sleep 60
```

**Comment by shlomitk1** [comment] 2022-06-13 19:27
Left to explore:
- Why are there 17 upgrades? Should not be any, given the fact that the 60 sec sleep interval was made to ensure that the pods are properly cleaned up. 
- There are frequent calls to check the status of the release and the resources. Can any improvements be made?

**Comment by shlomitk1** [comment] 2022-06-13 19:50
> @shlomitk1 what was `imagePullPolicy` during the tests ?

Of the manager pod? **Always** 
But I don't see the relevance to the helm installs and other operations that have been measured.

**Comment by roytman** [comment] 2022-06-13 19:51
According to the provided numbers, looks like there ware 67 iterations ( 50 installs + 17 upgrades ) as well 67 pulls and loads. Is it correct ?

**Comment by roytman** [comment] 2022-06-13 19:52
> > @shlomitk1 what was `imagePullPolicy` during the tests ?
> 
> Of the manager pod? **Always** But I don't see the relevance to the helm installs and other operations that have been measured.

The module's pod

**Comment by shlomitk1** [comment] 2022-06-13 19:57
> According to the provided numbers, looks like there ware 67 iterations ( 50 installs + 17 upgrades ) as well 67 pulls and loads. Is it correct ?

50 iterations of the script I have attached above. No idea where the upgrades are coming from. Originally, there was a smaller interval between deleting an app and applying a new one, so I suspected a release was being attempted to install and failed because the old pod did not die yet. Maybe this is still the reason. I'll try to run with even a bigger time interval.

**Comment by shlomitk1** [comment] 2022-06-13 19:59
> > > @shlomitk1 what was `imagePullPolicy` during the tests ?
> > 
> > 
> > Of the manager pod? **Always** But I don't see the relevance to the helm installs and other operations that have been measured.
> 
> The module's pod

**Always**

**Comment by roytman** [comment] 2022-06-13 19:59
>  I suspected a release was being attempted to install and failed because the old pod did not die yet. 

Can we check errors in the logs ?

**Comment by roytman** [comment] 2022-06-13 20:20
I'm looking on the numbers, there is something strange in `duration per call` and `duration per app iteration`.
I can understand that if the same method was called several times per app iteration, the duration per app will be accommodated time, like in case of `status`.
How can you explain that `upgrade` took 8332.56 ms per call and 2833.07 per app iteration?

**Comment by roytman** [comment] 2022-06-13 20:39
> > > > @shlomitk1 what was `imagePullPolicy` during the tests ?
> > > 
> > > 
> > > Of the manager pod? **Always** But I don't see the relevance to the helm installs and other operations that have been measured.
> > 
> > 
> > The module's pod
> 
> **Always**

In order to compare results, can you repeat the test with `IfNotPresent` ?

**Comment by shlomitk1** [comment] 2022-06-14 05:25
> I'm looking at the numbers, there is something strange in `duration per call` and `duration per app iteration`. I can understand that if the same method was called several times per app iteration, the duration per app will be accommodated time, like in case of `status`. How can you explain that `upgrade` took 8332.56 ms per call and 2833.07 per app iteration?
> 
> Or it overlapped app iterations, and got wrong time.

Duration per app iteration is just an average of the total duration divided by 50. So for an upgrade of duration X we'll have 12X/50 in average. If you think it is a meaningless number, just ignore.

**Comment by simanadler** [comment] 2022-06-14 06:19
@shlomitk1 While it's fine to focus on helm, since that was the main thing taking time ... in addition please run the same tests as you did on 24 Nov 2021 so that we have a comparison to the previous version.

**Comment by shlomitk1** [comment] 2022-06-14 13:49
@roytman With pullImagePolicy = IfNotPresent:
![image](https://user-images.githubusercontent.com/70848285/173592464-d3acff84-434b-4811-9b93-dfb188160468.png)
Looks much better!

**Comment by roytman** [comment] 2022-06-14 18:28
Interesting, that status is 47.7 ms vs 362  and getResource is 218 vs 836. The pull image policy should not influence on these calls, or I'm missing something.

**Comment by shlomitk1** [comment] 2022-06-15 07:23
Rerunning with pullImagePolicy = Always:
![image](https://user-images.githubusercontent.com/70848285/173767330-a24b8b34-21d3-4c71-88bb-261a2fe309e5.png)

**Comment by shlomitk1** [comment] 2022-06-15 07:29
Results are looking pretty much comparable. Given the concurrent run of the controllers, I am not sure how accurate a single measurement is. The idea was to measure the end-to-end run. It makes more sense to compare imagePullPolicy values at the single helm operation level rather than the entire control plane.

**Comment by simanadler** [comment] 2022-06-15 11:53
@shlomitk1  A couple of questions:

1. In blueprint_controller.go, applyChartResource, line 240 we check the status of the chart in order to determine whether to install or upgrade.  Couldn't we skip this status check, and always use the Helm Upgrade command with [--install](https://helm.sh/docs/helm/helm_upgrade/)?  This upgrades if the chart exists, and if it doesn't it installs.

This would decrease the number of calls to Helm status, and would also simplify the code.

2. Why are there 280 calls to getResources?  It's used to check the status after deployment.  Right?  If so, you have to install, update, delete the arrow-flight-server I assume there is a status check after each.  That would give me 150, but your table shows 280.  What am I missing?

3. Why are there only 11 upgrade calls?  When you delete a data set doesn't that cause an upgrade to the arrow-flight helm chart?  

4. Why are there 61 pull and load calls?  

6. Any idea of the time it takes to log in/out of the registry?  I see in the code that we do it during every reconcile.  Wouldn't it be sufficient for the control plane to log in only once, or at least only once per FybrikApplication instance?  If the time is small we can ignore.

**Comment by shlomitk1** [comment] 2022-06-15 18:36
> @shlomitk1 A couple of questions:
> 

1. There is no use in setting an Install option for Upgrade. From the documentation (upgrade action):
```
// Install is a purely informative flag that indicates whether this upgrade was done in "install" mode.
	//
	// Applications may use this to determine whether this Upgrade operation was done as part of a
	// pure upgrade (Upgrade.Install == false) or as part of an install-or-upgrade operation
	// (Upgrade.Install == true).
	//
	// Setting this to `true` will NOT cause `Upgrade` to perform an install if the release does not exist.
	// That process must be handled by creating an Install action directly. See cmd/upgrade.go for an
	// example of how this flag is used.
	Install bool
```
2. GetResources is done in a "polling" mode, that's why it takes a number of calls until the release is ready. I need to check whether the "wait" option blocks the call until the release is ready. It did not work for me previously, but maybe with the latest version of Helm things have changed.

3. So here is the thing: there should be no upgrades at all. We have an extra reconcile somewhere (and I think I have found it) that causes the controller to attempt an install (upgrade) twice.
 
 4. 61 = 50+11, each `applyChartResource` method calls both load and install/upgrade. Ideally, there should be only 50.
 
 5. Regarding login/logout, I don't know. You'd need to store a helm chart in a private repository and supply pull secrets for obtaining the chart, to activate the login/logout functionality. Perhaps, @cdoron has some use cases that can be measured.

**Comment by roytman** [comment] 2022-06-16 03:33
Couple of comments:

1. > There is no use in setting an Install option for Upgrade. From the documentation (upgrade action): ....

The mentioned above [code comment](https://github.com/helm/helm/blob/657850e44b880cca43d0606ebf5a54eb75362c3f/pkg/action/upgrade.go#L48) is wrong. The comment suggests to check "cmd/upgrade.go for an example of how this flag is used". 
So `cmd/upgrade.go` [says](https://github.com/helm/helm/blob/657850e44b880cca43d0606ebf5a54eb75362c3f/cmd/helm/upgrade.go#L95) 
> // If a release does not exist, install it.

I ran entire Fybrik "Get Started" process with `upgrade --install` options instead of the `install` commands, all packages include fybrik itself were successfully installed. I'll submit a PR to remove the misleading comment.
  
  
2. > I need to check whether the "wait" option blocks the call until the release is ready. It did not work for me previously, but maybe with the latest version of Helm things have changed. 

I suggest to set both flags `Wait` and `WaitForJobs` to `true`.  (a module might include jobs).

3. The last one, jut put attention that we continue using `DisableOpenAPIValidation  =  true`. It was set when helm had the memory leak. For better robustness we need to unset it. In the previous performance tests it was `false`.

**Comment by shlomitk1** [comment] 2022-06-20 20:14
Rerunning the test after changes made by @roytman, with imagePullPolicy = IfNotPresent (the results are better than with Always):
![image](https://user-images.githubusercontent.com/70848285/174672138-6cd68ffe-f6aa-4588-b0ba-4f453e529b0e.png)

**Comment by shlomitk1** [comment] 2022-06-20 20:20
The number of status/getResources calls has been significantly removed after using install with wait option. However, the duration of an install operation has increased (9.4 sec vs 3.6 sec).
Future improvements: no need for checking "standard" resources after wait, removing extra reconciles/upgrades.
Also, since installing of a pod takes so much time, I'd suggest to test a module that installs config maps and services, for example.

**Comment by roytman** [comment] 2022-06-20 21:18
Actually, in the original code, when the install operation returned, the resources were not ready yet, and the entire process required several "getResources" iterations (each with a delay of 2 sec). Now the install command returns after finishing the entire process. 

@shlomitk1 do you have measurements from the original code, from start of installation until the resources were ready ? When you wrote "End-to-end scenario takes ~5s" what were the start and end of the probes ? 

If now, install requires 9.4 sec plus 2 sec getResources iteration delay (in the original code),  we are getting 11.4 sec which is going to be  close to the  BU results. 
We have to check how they  measure the process.

**Comment by roytman** [comment] 2022-06-20 21:29
@shlomitk1 could you check please if in the manager logs there is the following message "blueprint.Status.ObservedState is not ready, will try again" ? I want to validate that when `helm install --wait` returns, all resources are ready.

**Comment by shlomitk1** [comment] 2022-06-21 06:53
@roytman end-to-end scenaro for 5 sec was on kind, installing a pod was not much slower than installing a configmap, on open-shift run-times are different.
Current measurements show ~11 sec.

**Comment by shlomitk1** [comment] 2022-06-21 06:57
> blueprint.Status.ObservedState is not ready, will try again

I did not find this message. Found those instead: `Deployment is not ready: fybrik-blueprints/demo-app-default-arrow-flight-module-arrow-flight-module-chart. 0 out of 1 expected pods are ready`

**Comment by roytman** [comment] 2022-06-21 07:34
the latest message is printed by helm when it is waiting and checking readiness of the objects

**Comment by shlomitk1** [comment] 2022-06-21 11:07
> I understood difference between kind and OpenShif, my question is where are the start and end probe points? Is it the entire reconcile loop? something else ?

From the first reconcile after the app was created until the app gets a ready condition

**Comment by roytman** [comment] 2022-06-21 12:28
Here are the helmer operations on an OpenShift cluster datamesh05 , the installed chart is our arrow-flight module,  which was preloaded into a local dir, the test ran 100 iterations. Time in ms:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/1816654/174799085-33442040-1af0-4184-807b-2ba223bc1bf6.png">

**Comment by shlomitk1** [comment] 2022-08-15 12:17
Performance improvements have been made. Closing this issue.

**Closed by shlomitk1** 2022-08-15 12:17 UTC
