### ISSUE TITLE
make install-tools error

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#1692] opened 2022-08-16 06:47 UTC
I have a new (intel based)mac and when I run make install-tools I get the following error:

Installing bin/fzn-or-tools 9.2.9972
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0     18      0 --:--:-- --:--:-- --:--:--    18
tar: Error opening archive: Unrecognized archive format
rm: or-tools__flatzinc_MacOsX-12.2.1_v9.2.9972.tar.gz: No such file or directory
rm: or-tools__flatzinc_MacOsX-12.2.1_v9.2.9972.tar.gz: No such file or directory
make: *** [hack/tools/bin/fzn-or-tools] Error 1

**Comment by shlomitk1** [comment] 2022-08-19 09:38
Duplicate of https://github.com/fybrik/fybrik/issues/1525

**Comment by roytman** [comment] 2023-01-02 11:42
closed as duplicated

**Closed by roytman** 2023-01-02 11:42 UTC
Labels: bug, duplicate
